name: Deploy To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for local use only)
        uses: actions/checkout@v2

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
          
            cd ./gentleman-backend
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d